server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

jwt:
  secret: BankingMicroservicesAuthServiceJwtSecretKeyForHS512ChangeInProduction2026
eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka/

zipkin:
  base-url: http://zipkin:9411
  
