server:
  port: 8080

spring:
  application:
    name: api-gateway

jwt:
  secret: mySuperSecretKey123456
eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka/

zipkin:
  base-url: http://zipkin:9411
  