server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/auth_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: BankingSystemSecretKeyChangeInProduction
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka/